### ISSUE TITLE
copy_db.php niet te vinden

### ISSUE THREAD

**Issue by KjellVerb** [WilfriedBieseman/p1monitor-kwartiervermogen#1]
In de gecomprimeerde archives van release 2.2 zit geen copy_db.php file

**Comment by WilfriedBieseman** [comment]
copy_db.php is dezelfde als in de eerste release.
De telegram die uit de slimme meter komt is sinds 1 januari wat aangepast, waardoor er noodzaak is aan een volgende release (voorzien eind februari - begin maart. Ik pas het geheel dan aan en ook de kwartierpieken die blijkbaar ELKE maand minstens 2.5 kW moeten bedragen om het gemiddelde te berekenen. Ik probeer ook een Anrdroid-app te ontwerpen.

**Comment by KjellVerb** [comment]
Ok got it!
Klinkt goed, ik begrijp nu ook waarom kartiervermogen.php faalt :-)
